# Generated by Django 5.2.13 on 2026-05-01 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('unit', models.CharField(choices=[('kg', 'Килограмм'), ('g', 'Грамм'), ('l', 'Литр'), ('ml', 'Миллилитр')], max_length=10, verbose_name='Единица измерения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сырьё',
                'verbose_name_plural': 'Сырьё',
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, unique=True, verbose_name='Номер партии')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Остаток')),
                ('received_at', models.DateField(verbose_name='Дата поступления')),
                ('expiry_date', models.DateField(verbose_name='Срок годности')),
                ('status', models.CharField(choices=[('available', 'Доступна'), ('depleted', 'Израсходована'), ('expired', 'Просрочена')], default='available', max_length=20)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.ingredient', verbose_name='Сырьё')),
            ],
            options={
                'verbose_name': 'Партия сырья',
                'verbose_name_plural': 'Партии сырья',
                'ordering': ['expiry_date'],
            },
        ),
    ]
