# Generated by Django 5.2.13 on 2026-05-02 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Списано')),
                ('written_off_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата списания')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.batch', verbose_name='Партия')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.productionorder', verbose_name='Заказ')),
                ('written_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто списал')),
            ],
            options={
                'verbose_name': 'Запись списания',
                'verbose_name_plural': 'Журнал списания',
                'ordering': ['-written_off_at'],
            },
        ),
    ]
