# Generated by Django 5.2.13 on 2026-05-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_writeofflog'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='min_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Минимальный остаток'),
        ),
    ]
