# Generated by Django 5.2.13 on 2026-05-01 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество, шт')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'Ожидание сырья'), ('in_progress', 'В работе'), ('done', 'Завершён'), ('cancelled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('due_date', models.DateField(verbose_name='Срок выпуска')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Производственный заказ',
                'verbose_name_plural': 'Производственные заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
