# Generated by Django 5.2.13 on 2026-05-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity_per_unit',
            field=models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Норма на 1 шт'),
        ),
    ]
